# Generated by Django 5.1.5 on 2026-01-19 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_passenger', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('super_admin', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'accounts_admin',
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='face_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('face_image', models.ImageField(help_text='Primary face image used for enrollment', upload_to='face_profiles/')),
                ('face_encoding', models.TextField(blank=True, help_text='JSON-encoded facial embedding vector')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the face profile has been verified')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_quality_score', models.FloatField(default=0.0, help_text='Quality score of the enrolled face image (0-1)')),
                ('model_name', models.CharField(default='Facenet', help_text='Face recognition model used (Facenet, VGG-Face, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Face Profile',
                'verbose_name_plural': 'Face Profiles',
                'db_table': 'accounts_face_profile',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passenger_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('frequent_routes', models.JSONField(blank=True, default=list)),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'accounts_passenger',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('communication_preferences', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('active_tickets', models.IntegerField(default=0)),
                ('shift_timings', models.JSONField(blank=True, default=dict)),
                ('reporting_to_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'accounts_staff',
            },
        ),
        migrations.CreateModel(
            name='FaceEnrollmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('images_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Enrollment Session',
                'verbose_name_plural': 'Face Enrollment Sessions',
                'db_table': 'accounts_face_enrollment_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.ImageField(help_text='Image captured during authentication attempt', upload_to='face_auth_logs/')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('low_confidence', 'Low Confidence Match'), ('not_enrolled', 'User Not Enrolled')], default='failed', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Match confidence score (0-1, higher is better)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('matched_user_email', models.EmailField(blank=True, help_text='Email of matched user (for logging)', max_length=254)),
                ('model_used', models.CharField(default='Facenet', help_text='Face recognition model used for this attempt', max_length=50)),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Time taken to process authentication (milliseconds)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Identified user (null if not recognized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Auth Log',
                'verbose_name_plural': 'Face Auth Logs',
                'db_table': 'accounts_face_auth_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_fa_timesta_dd283b_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_fa_user_id_821560_idx'), models.Index(fields=['status', '-timestamp'], name='accounts_fa_status_9f1c6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('complaints_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='accounts.staff')),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performance',
                'db_table': 'accounts_staff_performance',
                'ordering': ['-year', '-month'],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_break', 'On Break'), ('offline', 'Offline')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='accounts.staff')),
            ],
            options={
                'verbose_name': 'Staff Availability',
                'verbose_name_plural': 'Staff Availability',
                'db_table': 'accounts_staff_availability',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
