# Generated by Django 5.1.5 on 2025-08-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_firebaseuser_user_type'),
        ('accounts', '0002_firebaseuser_is_super_admin'),
    ]

    operations = [
    ]
