# Generated by Django 5.1.5 on 2025-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250810_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='is_passenger',
            field=models.BooleanField(default=True),
        ),
    ]
