# Generated by Django 5.1.5 on 2025-10-03 06:23

from django.db import migrations

def update_user_roles(apps, schema_editor):
    """Update user roles based on your database data"""
    FirebaseUser = apps.get_model('accounts', 'FirebaseUser')
    
    # Based on your database dump, let's update the roles
    users_to_update = [
        # Admin users
        ('akram.dcme@gmail.com', {'is_admin': True, 'is_staff': True, 'is_passenger': False}),
        ('22BQ1A4225@vvit.net', {'is_admin': True, 'is_staff': True, 'is_passenger': False}),
        ('adm.railmadad@gmail.com', {'is_admin': True, 'is_staff': True, 'is_passenger': False}),
        ('chandragirimanojkrishna@gmail.com', {'is_admin': True, 'is_staff': True, 'is_passenger': False}),
        ('manojkrishna991@gmail.com', {'is_admin': True, 'is_staff': True, 'is_passenger': False}),
        
        # Passenger users (default)
        ('chandragirimanoj999@gmail.com', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
        ('akramnaeemuddshaik@gmail.com', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
        ('manojkrishnachandragiri@gmail.com', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
        ('22bq1a05k3@gmail.com', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
        ('22bq1a4224@vvit.net', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
        ('23bq5a4204@vvit.net', {'is_passenger': True, 'is_admin': False, 'is_staff': False}),
    ]
    
    for email, roles in users_to_update:
        try:
            user = FirebaseUser.objects.get(email=email)
            for field, value in roles.items():
                setattr(user, field, value)
            user.save()
            print(f"Updated {email}: {roles}")
        except FirebaseUser.DoesNotExist:
            print(f"User {email} not found, skipping...")

def reverse_update_user_roles(apps, schema_editor):
    """Reverse the migration if needed"""
    FirebaseUser = apps.get_model('accounts', 'FirebaseUser')
    # Reset all users to passenger by default
    FirebaseUser.objects.all().update(
        is_passenger=True,
        is_admin=False, 
        is_staff=False,
        is_super_admin=False
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_firebaseuser_user_type_and_more'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, reverse_update_user_roles),
    ]
