# Generated by Django 5.1.5 on 2025-12-27 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_migrate_existing_data'),
    ]

    operations = [
        # Create Admin table
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=models.CASCADE,
                    primary_key=True,
                    related_name='admin_profile',
                    serialize=False,
                    to='accounts.firebaseuser'
                )),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('super_admin', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'accounts_admin',
            },
        ),
        
        # Create Staff table
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=models.CASCADE,
                    primary_key=True,
                    related_name='staff_profile',
                    serialize=False,
                    to='accounts.firebaseuser'
                )),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(
                    choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')],
                    default='active',
                    max_length=20
                )),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('communication_preferences', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('active_tickets', models.IntegerField(default=0)),
                ('shift_timings', models.JSONField(blank=True, default=dict)),
                ('reporting_to_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'accounts_staff',
            },
        ),
        
        # Create Passenger table
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=models.CASCADE,
                    primary_key=True,
                    related_name='passenger_profile',
                    serialize=False,
                    to='accounts.firebaseuser'
                )),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(
                    blank=True,
                    choices=[
                        ('male', 'Male'),
                        ('female', 'Female'),
                        ('other', 'Other'),
                        ('prefer_not_to_say', 'Prefer not to say')
                    ],
                    max_length=20
                )),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('frequent_routes', models.JSONField(blank=True, default=list)),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'accounts_passenger',
            },
        ),
        
        # Create StaffAvailability table
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(
                    choices=[
                        ('scheduled', 'Scheduled'),
                        ('on_duty', 'On Duty'),
                        ('completed', 'Completed'),
                        ('cancelled', 'Cancelled')
                    ],
                    default='scheduled',
                    max_length=20
                )),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Staff Availability',
                'verbose_name_plural': 'Staff Availability',
                'db_table': 'accounts_staff_availability',
                'unique_together': {('staff_id', 'date', 'shift_start')},
            },
        ),
        
        # Create StaffPerformance table
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('complaints_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performance Records',
                'db_table': 'accounts_staff_performance',
                'unique_together': {('staff_id', 'month', 'year')},
            },
        ),
    ]
