# Generated by Django 5.1.5 on 2025-12-27 09:51

from django.db import migrations
from django.db.models import Q


def migrate_admins(apps, schema_editor):
    """Migrate admin users from FirebaseUser to Admin table"""
    FirebaseUser = apps.get_model('accounts', 'FirebaseUser')
    Admin = apps.get_model('accounts', 'Admin')
    
    # Find all admin users
    admin_users = FirebaseUser.objects.filter(
        Q(is_admin=True) | Q(is_super_admin=True)
    )
    
    print(f"Migrating {admin_users.count()} admin users...")
    
    for user in admin_users:
        # Check if admin profile already exists
        if not Admin.objects.filter(user=user).exists():
            Admin.objects.create(
                user=user,
                full_name=user.full_name or user.email.split('@')[0],
                phone_number=user.phone_number or '',
                department='',
                designation='',
                employee_id=None,
                super_admin=user.is_super_admin if hasattr(user, 'is_super_admin') else False,
                permissions=['all'] if (hasattr(user, 'is_super_admin') and user.is_super_admin) else []
            )
            print(f"Created admin profile for: {user.email}")


def migrate_staff_from_old_table(apps, schema_editor):
    """Migrate staff from complaints_staff table to accounts_staff"""
    from django.db import connection
    
    FirebaseUser = apps.get_model('accounts', 'FirebaseUser')
    Staff = apps.get_model('accounts', 'Staff')
    
    # Get data from old complaints_staff table
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, name, email, phone, role, department, location, 
                   avatar, status, joining_date, expertise, rating, 
                   active_tickets, languages, communication_preferences
            FROM complaints_staff
        """)
        
        old_staff = cursor.fetchall()
    
    print(f"Migrating {len(old_staff)} staff members...")
    
    for staff_data in old_staff:
        (old_id, name, email, phone, role, department, location, 
         avatar, status, joining_date, expertise, rating, 
         active_tickets, languages, comm_prefs) = staff_data
        
        # Find or create FirebaseUser for this staff
        user, created = FirebaseUser.objects.get_or_create(
            email=email,
            defaults={
                'firebase_uid': f'staff_{old_id}_{email}',
                'is_active': True,
            }
        )
        
        if created:
            print(f"Created FirebaseUser for staff: {email}")
        
        # Create Staff profile if doesn't exist
        if not Staff.objects.filter(user=user).exists():
            # Parse JSON fields
            import json
            expertise_list = json.loads(expertise) if expertise and isinstance(expertise, str) else (expertise or [])
            languages_list = json.loads(languages) if languages and isinstance(languages, str) else (languages or [])
            comm_prefs_list = json.loads(comm_prefs) if comm_prefs and isinstance(comm_prefs, str) else (comm_prefs or ['Chat'])
            
            Staff.objects.create(
                user=user,
                full_name=name,
                phone_number=phone or '',
                employee_id=f'EMP{old_id:04d}',
                department=department or 'General',
                role=role or 'staff',
                location=location or '',
                avatar=avatar or '',
                status=status or 'active',
                joining_date=joining_date,
                expertise=expertise_list,
                languages=languages_list,
                communication_preferences=comm_prefs_list,
                rating=rating or 0.0,
                active_tickets=active_tickets or 0,
                shift_timings={},
                reporting_to_id=None
            )
            print(f"Created staff profile for: {name} ({email})")


def migrate_passengers(apps, schema_editor):
    """Migrate passenger users from FirebaseUser to Passenger table"""
    FirebaseUser = apps.get_model('accounts', 'FirebaseUser')
    Passenger = apps.get_model('accounts', 'Passenger')
    
    # Find all passenger users
    passenger_users = FirebaseUser.objects.filter(is_passenger=True)
    
    print(f"Migrating {passenger_users.count()} passenger users...")
    
    for user in passenger_users:
        # Check if passenger profile already exists
        if not Passenger.objects.filter(user=user).exists():
            Passenger.objects.create(
                user=user,
                full_name=user.full_name or '',
                phone_number=user.phone_number or '',
                gender=user.gender if hasattr(user, 'gender') else '',
                date_of_birth=None,
                address=user.address if hasattr(user, 'address') else '',
                city='',
                state='',
                pincode='',
                preferred_language='en',
                notification_preferences={},
                frequent_routes=[],
                total_complaints=0,
                resolved_complaints=0
            )
            print(f"Created passenger profile for: {user.email}")


def reverse_migration(apps, schema_editor):
    """Reverse migration - for rollback"""
    Admin = apps.get_model('accounts', 'Admin')
    Staff = apps.get_model('accounts', 'Staff')
    Passenger = apps.get_model('accounts', 'Passenger')
    
    print("Rolling back role table migrations...")
    Admin.objects.all().delete()
    Staff.objects.all().delete()
    Passenger.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_create_role_tables'),
    ]

    operations = [
        migrations.RunPython(migrate_admins, reverse_migration),
        migrations.RunPython(migrate_staff_from_old_table, reverse_migration),
        migrations.RunPython(migrate_passengers, reverse_migration),
    ]
