# Generated by Django 5.1.5 on 2025-12-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_populate_role_emails'),
        ('complaints', '0021_remove_complaint_assigned_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffshift',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'ordering': ['-date'], 'verbose_name': 'Staff Availability', 'verbose_name_plural': 'Staff Availability'},
        ),
        migrations.AlterModelOptions(
            name='staffperformance',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Staff Performance', 'verbose_name_plural': 'Staff Performance'},
        ),
        migrations.RemoveIndex(
            model_name='firebaseuser',
            name='accounts_fi_email_user_type_idx',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='user_type',
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='staffperformance',
            unique_together={('staff', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='complaints.staff'),
        ),
        migrations.AddField(
            model_name='staffperformance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='complaints.staff'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_break', 'On Break'), ('offline', 'Offline')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
        migrations.RemoveField(
            model_name='staffavailability',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='staffperformance',
            name='staff_id',
        ),
    ]
