# Generated by Django 5.1.5 on 2025-12-29 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_staffshift_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='face_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('face_image', models.ImageField(help_text='Primary face image used for enrollment', upload_to='face_profiles/')),
                ('face_encoding', models.TextField(blank=True, help_text='JSON-encoded facial embedding vector')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the face profile has been verified')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_quality_score', models.FloatField(default=0.0, help_text='Quality score of the enrolled face image (0-1)')),
                ('model_name', models.CharField(default='Facenet', help_text='Face recognition model used (Facenet, VGG-Face, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Face Profile',
                'verbose_name_plural': 'Face Profiles',
                'db_table': 'accounts_face_profile',
            },
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='staffperformance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='accounts.staff'),
        ),
        migrations.CreateModel(
            name='FaceEnrollmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('images_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Enrollment Session',
                'verbose_name_plural': 'Face Enrollment Sessions',
                'db_table': 'accounts_face_enrollment_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.ImageField(help_text='Image captured during authentication attempt', upload_to='face_auth_logs/')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('low_confidence', 'Low Confidence Match'), ('not_enrolled', 'User Not Enrolled')], default='failed', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Match confidence score (0-1, higher is better)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('matched_user_email', models.EmailField(blank=True, help_text='Email of matched user (for logging)', max_length=254)),
                ('model_used', models.CharField(default='Facenet', help_text='Face recognition model used for this attempt', max_length=50)),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Time taken to process authentication (milliseconds)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Identified user (null if not recognized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Auth Log',
                'verbose_name_plural': 'Face Auth Logs',
                'db_table': 'accounts_face_auth_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_fa_timesta_dd283b_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_fa_user_id_821560_idx'), models.Index(fields=['status', '-timestamp'], name='accounts_fa_status_9f1c6b_idx')],
            },
        ),
    ]
