# Generated by Django 5.0.1 on 2026-01-28 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_by', models.CharField(max_length=255)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('success', 'Successfully Resolved'), ('partial', 'Partially Resolved'), ('failed', 'Failed to Resolve'), ('escalated', 'Escalated to Support')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('resolution_time_actual', models.IntegerField(blank=True, null=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.quicksolution')),
            ],
            options={
                'verbose_name_plural': 'Solution Applications',
            },
        ),
    ]
