# Generated by Django 5.1.5 on 2025-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_quicksolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
