# Generated by Django 5.1.5 on 2025-12-27 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_feedback_sentiment_feedback_sentiment_confidence'),
        ('accounts', '0010_migrate_data_to_role_tables'),
    ]

    operations = [
        # Create ComplaintAssignment table
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField()),
                ('staff_id', models.IntegerField()),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(
                    choices=[
                        ('assigned', 'Assigned'),
                        ('in_progress', 'In Progress'),
                        ('escalated', 'Escalated'),
                        ('completed', 'Completed'),
                        ('reassigned', 'Reassigned')
                    ],
                    default='assigned',
                    max_length=20
                )),
                ('notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Complaint Assignment',
                'verbose_name_plural': 'Complaint Assignments',
                'db_table': 'complaints_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        
        # Add new fields to Complaint table
        migrations.AddField(
            model_name='complaint',
            name='assigned_staff_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='passenger_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
