# Generated by Django 5.1.5 on 2025-12-27 09:53

from django.db import migrations


def migrate_complaint_assignments(apps, schema_editor):
    """Migrate complaint user relationships and create assignments"""
    from django.db import connection
    
    Complaint = apps.get_model('complaints', 'Complaint')
    ComplaintAssignment = apps.get_model('complaints', 'ComplaintAssignment')
    
    print("Migrating complaint assignments...")
    
    # Update passenger_id for all complaints
    with connection.cursor() as cursor:
        # Link complaints to passengers
        cursor.execute("""
            UPDATE complaints_complaint cc
            INNER JOIN accounts_passenger ap ON cc.user_id = ap.user_id
            SET cc.passenger_id = ap.user_id
            WHERE cc.user_id IS NOT NULL
        """)
        print(f"Updated {cursor.rowcount} complaints with passenger_id")
        
        # Parse staff assignments from the old 'staff' field
        cursor.execute("""
            SELECT id, staff, user_id 
            FROM complaints_complaint 
            WHERE staff IS NOT NULL AND staff != ''
        """)
        
        complaints_with_staff = cursor.fetchall()
    
    print(f"Processing {len(complaints_with_staff)} complaints with staff assignments...")
    
    for complaint_id, staff_name, user_id in complaints_with_staff:
        if not staff_name:
            continue
            
        # Try to find matching staff by name or department
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT user_id FROM accounts_staff 
                WHERE full_name LIKE %s OR department LIKE %s
                LIMIT 1
            """, [f'%{staff_name}%', f'%{staff_name}%'])
            
            staff_match = cursor.fetchone()
            
            if staff_match:
                staff_id = staff_match[0]
                
                # Update complaint with assigned_staff_id
                Complaint.objects.filter(id=complaint_id).update(assigned_staff_id=staff_id)
                
                # Create assignment record
                ComplaintAssignment.objects.create(
                    complaint_id=complaint_id,
                    staff_id=staff_id,
                    assigned_by_id=None,  # Historical data, no assigner
                    status='in_progress',
                    notes=f'Migrated from old staff field: {staff_name}'
                )
                print(f"Created assignment: Complaint {complaint_id} -> Staff {staff_id}")


def reverse_migration(apps, schema_editor):
    """Reverse migration"""
    ComplaintAssignment = apps.get_model('complaints', 'ComplaintAssignment')
    print("Rolling back complaint assignments...")
    ComplaintAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_create_assignment_table'),
        ('accounts', '0010_migrate_data_to_role_tables'),
    ]

    operations = [
        migrations.RunPython(migrate_complaint_assignments, reverse_migration),
    ]
