# Generated by Django 5.1.5 on 2025-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_migrate_complaint_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_by_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_staff_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='passenger_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='performance_metrics',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
