# Generated by Django 5.1.5 on 2025-12-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0021_add_staff_to_feedback'),
        ('complaints', '0021_remove_complaint_assigned_by_id_and_more'),
    ]

    operations = [
    ]
