# Generated by Django 5.1.5 on 2025-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='has_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
