# Generated by Django 5.1.5 on 2026-01-01 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0024_complaint_has_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('status_updates', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('announcements', models.BooleanField(default=True)),
                ('feedback_notifications', models.BooleanField(default=True)),
                ('assignment_notifications', models.BooleanField(default=True)),
                ('resolution_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
